server.port=8080

# Conexión JDBC a la base de datos de Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/corewatch_db
spring.datasource.username=corewatch_user
spring.datasource.password=corewatch_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración del ORM Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
